import path from "node:path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    include: ["**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    exclude: [
      "node_modules",
      "dist",
      "dist-electron",
      "build",
      "release",
      ".kilo",
      ".worktrees",
      "vendor",
      "scripts/__tests__/mcp-bridge-forgery.test.mjs",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      exclude: [
        "node_modules/",
        "src/test/",
        ".kilo/",
        ".worktrees/",
        "dist/",
        "dist-electron/",
        "src/components/",
        "src/views/",
        "src/ui/",
        "App.tsx",
        "index.tsx",
        "src/assets/logo.png",
        "src/context/KeybindingContext.tsx",
        "src/contexts/ConfirmationContext.tsx",
        "src/core/api/localApi.ts",
        "src/core/board/deriveAttentionLane.ts",
        "src/core/events/taskEventReducer.ts",
        "src/core/events/taskEventStore.ts",
        "src/hooks/useAgentStandupDigest.ts",
        "src/hooks/useAgentTaskStatus.ts",
        "src/hooks/useAgentTeammateWiring.ts",
        "src/hooks/useAgentTeammates.ts",
        "src/hooks/useAiKeyboardShortcuts.ts",
        "src/hooks/useAppInitialization.ts",
        "src/hooks/useAppKeyboardOrchestration.ts",
        "src/hooks/useAppSurface.ts",
        "src/hooks/useAutoArchive.ts",
        "src/hooks/useAutomationSchedulerContext.ts",
        "src/hooks/useBoardDnDController.ts",
        "src/hooks/useBoardKeyboardNav.ts",
        "src/hooks/useCampaign.ts",
        "src/hooks/useDeadLetterInbox.ts",
        "src/hooks/useDevCouncilWorkspaceSync.ts",
        "src/hooks/useDragAndDrop.ts",
        "src/hooks/useFocusTrap.ts",
        "src/hooks/useGitHubSync.ts",
        "src/hooks/useGlobalKeyboardShortcuts.ts",
        "src/hooks/useKeyboardNav.ts",
        "src/hooks/useLiquidBlobPhysics.ts",
        "src/hooks/useSearchHistory.ts",
        "src/hooks/useSessionDiscoveryInbox.ts",
        "src/hooks/useTaskAssistant.ts",
        "src/hooks/useTaskCardContextMenu.ts",
        "src/hooks/useTaskController.ts",
        "src/hooks/useTaskForm.tsx",
        "src/runtime/coreDto.ts",
        "src/runtime/runtimeEnvironment.ts",
        "src/services/aiService.ts",
        "src/services/aiSummaryService.ts",
        "src/services/archiveService.ts",
        "src/services/autoOrganizeService.ts",
        "src/services/automationService.ts",
        "src/services/deadLetterService.ts",
        "src/services/encryptionSetup.ts",
        "src/services/exportService.ts",
        "src/services/githubSyncService.ts",
        "src/services/indexedDBService.ts",
        "src/services/migrationService.ts",
        "src/services/nativeBridge.ts",
        "src/services/notificationService.ts",
        "src/services/recurringTaskService.ts",
        "src/services/remotePushNotificationService.ts",
        "src/services/searchIndexService.ts",
        "src/services/semanticLayerService.ts",
        "src/services/sqliteTaskStore.ts",
        "src/services/storageService.ts",
        "src/services/templateService.ts",
        "src/services/timeReportingService.ts",
        "src/services/agents/agentAnalyticsService.ts",
        "src/services/agents/agentDispatchService.ts",
        "src/services/agents/agentEstimateLearningService.ts",
        "src/services/agents/agentMcpService.ts",
        "src/services/agents/agentPlannerService.ts",
        "src/services/agents/agentPolicyService.ts",
        "src/services/agents/agentPtyService.ts",
        "src/services/agents/agentReservationService.ts",
        "src/services/agents/agentRunService.ts",
        "src/services/agents/agentScopeService.ts",
        "src/services/agents/agentService.ts",
        "src/services/agents/agentSkillsService.ts",
        "src/services/agents/boardSnapshotService.ts",
        "src/services/agents/campaignMailbox.ts",
        "src/services/agents/campaignNotify.ts",
        "src/services/agents/campaignOrchestratorService.ts",
        "src/services/agents/devcouncilService.ts",
        "src/services/agents/feedbackLoopService.ts",
        "src/services/agents/reviewerRoleService.ts",
        "src/services/agents/runTraceService.ts",
        "src/services/agents/sessionDiscoveryService.ts",
        "src/services/agents/sessionForkService.ts",
        "src/services/agents/userMcpConfigService.ts",
        "src/services/agents/workspaceGitignoreInjector.ts",
        "src/services/agents/workspaceSkillsInjector.ts",
        "src/utils/aiModalTrust.ts",
        "src/utils/boardColumns.ts",
        "src/utils/gpuDetection.ts",
        "src/utils/keyboardTarget.ts",
        "src/utils/notificationPreferences.ts",
        "src/utils/persistStorage.ts",
        "src/utils/pushNotificationConfig.ts",
        "src/utils/queryEngine.ts",
        "src/utils/runProgress.ts",
        "src/utils/safeUrl.ts",
        "src/utils/taskParser.ts",
        "src/utils/taskSearch.ts",
      ],
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "."),
    },
  },
});
